version: '3'
services:
  my-app:
    #image: 939587331450.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
    image: my-app:1.0
    ports: 
      - 3000:3000
<<<<<<< HEAD
=======
    depends_on:
      - mongo-express
>>>>>>> 93e34c3f8e0ef949dc9ea625415990b3976fff4c
  mongodb:
    image: mongo:4.2.1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
<<<<<<< HEAD
=======
    depends_on:
      - mongodb

>>>>>>> 93e34c3f8e0ef949dc9ea625415990b3976fff4c
